let Employees=[{"Id":1,"Name":"Othilie","Email":"ocranham0@scientificamerican.com","gender":"Female"},
{"Id":2,"Name":"Daron","Email":"djervis1@webeden.co.uk","gender":"Male"},
{"Id":3,"Name":"Philis","Email":"pwardingly2@taobao.com","gender":"Female"},
{"Id":4,"Name":"Neel","Email":"nmussotti3@pcworld.com","gender":"Male"},
{"Id":5,"Name":"Felix","Email":"fcomo4@home.pl","gender":"Male"},
{"Id":6,"Name":"Jocelin","Email":"jwintersgill5@prlog.org","gender":"Female"},
{"Id":7,"Name":"Hansiain","Email":"hsawyers6@opensource.org","gender":"Male"},
{"Id":8,"Name":"Justin","Email":"jwealleans7@taobao.com","gender":"Male"},
{"Id":9,"Name":"Carolyn","Email":"ctroth8@webs.com","gender":"Female"},
{"Id":10,"Name":"Kandace","Email":"kcorby9@friendfeed.com","gender":"Female"},
{"Id":11,"Name":"Janina","Email":"jdudmana@blogtalkradio.com","gender":"Female"},
{"Id":12,"Name":"Gwendolyn","Email":"gmcowanb@mozilla.com","gender":"Female"},
{"Id":13,"Name":"Maisey","Email":"mmackenneyc@nps.gov","gender":"Female"},
{"Id":14,"Name":"Wilmette","Email":"wrosoned@examiner.com","gender":"Female"},
{"Id":15,"Name":"Leicester","Email":"lvannuccinie@macromedia.com","gender":"Male"},
{"Id":16,"Name":"Dara","Email":"dschlaghf@adobe.com","gender":"Female"},
{"Id":17,"Name":"Faustine","Email":"fmadging@ycombinator.com","gender":"Female"},
{"Id":18,"Name":"Timofei","Email":"tbarsonh@washingtonpost.com","gender":"Polygender"},
{"Id":19,"Name":"Avram","Email":"awhitelawi@ow.ly","gender":"Male"},
{"Id":20,"Name":"Lianne","Email":"lmilleryj@purevolume.com","gender":"Female"}]
export default Employees